### ISSUE TITLE
Send Location? 

### ISSUE THREAD

**Issue by chitogamer96** [danielcardeenas/sulla#161]
How to repply location?

**Comment by smashah** [comment]
That would be a pretty cool feature

**Comment by vasani-arpit** [comment]
Does web interface has that feature?

**Comment by smashah** [comment]
@vasani-arpit  No it doesn't.

I've figured out how to add a message to the web interface chat instance however due to issues in wapi.js itself, it does not actually send the message.

Try out the code in the web interface. Will update when we figure out the wapi.js issue.

Blocking error: https://github.com/mukulhase/WebWhatsapp-Wrapper/issues/779

Prelim commit: https://github.com/smashah/sulla/commit/8403f7e5cf008b5ecc9553fc8caaa4b9ca6f3171

**Comment by smashah** [comment]
Great news @vasani-arpit @chitogamer96 

I managed to figure out that ^ issue and now you can try sending location via sulla.

Check it out here: https://github.com/smashah/sulla#sending-location

**Comment by danielcardeenas** [comment]
About to add this feature in the next release

**Comment by danielcardeenas** [comment]
```javascript
client.sendLocation(message.from, 25.6801987, -100.4060626, 'Address tutle', 'Subtitle');
```
