### ISSUE TITLE
ReferenceError: WAPI is not defined

### ISSUE THREAD

**Issue by robertsLando** [danielcardeenas/sulla#212]
I'm getting this error and I'm unable to fix it. Any ideas? Has something changed on whatsapp web that has break apis?

**Comment by tomer8007** [comment]
Yeah, I managed to expose the API again using [moduleRain](https://github.com/pixeldesu/moduleRaid).

**Comment by robertsLando** [comment]
There is also a problem with chromium that needs to be updated. I'm going to submit a better pr for this

**Comment by robertsLando** [comment]
@tomer8007 Could you provide a better description please?

**Comment by tomer8007** [comment]
Apparently the code [here](https://github.com/danielcardeenas/sulla/blob/master/src/lib/wapi/wapi.js#L54) assumes that `webpackJsonp` is always a function, but recently (today) it looks like it is not a function anymore in WhatsApp Web - but an array instead. This means that now adding modules works differenly (you need to `push` them).

The moduleraid library is intended for extracting modules out of `webpack` pages, and it does so by taking care of `webpackJsonp` being both a function **and** an array. That's why it is able to extract the modules `waspi.js` can't.

**Comment by robertsLando** [comment]
@tomer8007 I have submitted a pr for that

**Comment by tomer8007** [comment]
Looks great

**Comment by danielcardeenas** [comment]
Thanks! Huge update coming today
![image](https://user-images.githubusercontent.com/2654812/78282976-566e8e80-74da-11ea-8d09-e47d6b80d8ae.png)

**Comment by danielcardeenas** [comment]
Also gonna need some maintainers. Would appreciate any help

**Comment by robertsLando** [comment]
Check my pr please and I’m +1 for maintainer

Daniel

**Comment by danielcardeenas** [comment]
Your code is included in the new release.

**Comment by robertsLando** [comment]
I don't see it merged anywhere that is why I'm asking, you mean that you will include it by your own or by merging my changes with your develop branch?

**Comment by danielcardeenas** [comment]
Install new version

To reply use:
```javascript
client.reply(message.from, '👋 Hello!', message.id.toString());
```
